### ISSUE TITLE
"import pyimplicitdist" has problem

### ISSUE THREAD

**Issue by liangshunkun** [cvg/implicit_dist#1]
Hi! i am very interested in your work on implicit distortion models, but i get some problem.
when i run "pip install .", i am sure the python binding has been complied successfully and the pyimplicitdis has been installed.
![image](https://user-images.githubusercontent.com/46750100/184476850-6d8c6c56-6e83-4fab-8daf-48d13bf22156.png)
however, when i "import pyimplicitdist" in my python3.7, i get a problem as followed:
![image](https://user-images.githubusercontent.com/46750100/184476948-8ab8bc90-5cfa-4f8f-bda3-14eccb36f6c3.png)
pycharm show that the package pyimplicitdist has been installed. i have no idea to deal with this problem and can you give a more detailed tutorial. thank you so much.
![image](https://user-images.githubusercontent.com/46750100/184477126-9e1d3630-39b9-418b-9fb4-94d0d305d3ff.png)

**Comment by Bobbypeng1** [comment]
did you solve this issue?

**Comment by lpanaf** [comment]
Sorry for the late reply. Have you checked whether your module is installed under the correct python version? Since the proper way to import the model should just be "import pyimplicitdist"

**Comment by lpanaf** [comment]
Since there are no further question, this question is closed
